<?php
/**
 * @file
 * Code for the GSB Feature Event feature.
 */

include_once 'gsb_feature_event.features.inc';

/**
 * Implementation of hook_form_FORM_ID_alter()
 *
 * Provides customizations to the views content type settings form
 */
function gsb_feature_event_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form["display_settings"])) {
    if (isset($form["display_settings"]["view_settings"])) {
      $form["display_settings"]["view_settings"]['#access'] = FALSE;
    }
    if (isset($form["display_settings"]["header_type"])) {
      $form["display_settings"]["header_type"]['#access'] = FALSE;
    }    
  }
  if (isset($form["content_settings"])) {
    $form["content_settings"]['#access'] = FALSE;
  }
}

/**
 * Implementation of hook_module_implements_alter()
 */
function gsb_feature_event_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['gsb_feature_event'])) {
      $group = $implementations['gsb_feature_event'];
      unset($implementations['gsb_feature_event']);
      $implementations['gsb_feature_event'] = $group;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for event node edit form.
 */
function gsb_feature_event_form_gsb_event_node_form_alter(&$form, &$form_state) {

  $index = 0;

  while (isset($form['field_speakers']['und'][$index])) {

    $form['field_speakers']['und'][$index]['field_speaker']['#states']['visible'][':input[name="field_speakers[und][' . $index . '][field_speaker_reference][und]"]'] = array(
      array('value' => 'UseEntityReference'),
    );

    $form['field_speakers']['und'][$index]['field_speaker_first_name']['#states']['visible'][':input[name="field_speakers[und][' . $index . '][field_speaker_reference][und]"]'] = array(
      array('value' => 'Custom'),
    );

    $form['field_speakers']['und'][$index]['field_speaker_last_name']['#states']['visible'][':input[name="field_speakers[und][' . $index . '][field_speaker_reference][und]"]'] = array(
      array('value' => 'Custom'),
    );

    $index++;

  }

}
